version: '3'
services:
  angular:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  spring:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

